### ISSUE TITLE
Add @cgobat and @katecrombie to @pds-data-dictionaries/nh-ldd-stewardship-team

### ISSUE THREAD

**Issue by cgobat** [pds-data-dictionaries/ldd-nh#10]
@katecrombie and I are leading the PDS4 development effort for *New Horizons*' upcoming K7 delivery. We need to be added to this dictionary's stewardship team in order to continue work on this LDD.

I am opening an issue here directly instead of in [pds-data-dictionaries/PDS4-LDD-Issue-Repo](/pds-data-dictionaries/PDS4-LDD-Issue-Repo) since this is an administrative/meta thing having to do with the repository itself. I am happy to move it if that is wrong.

**Comment by jordanpadams** [comment]
Done
