### ISSUE TITLE
decision on "to be updated/fixed/ more info added" flag

### ISSUE THREAD

**Issue by katecrombie** [pds-data-dictionaries/ldd-nh#15]
Let's agree on our flag for attribute or class definitions that need work.  Following the discussion on previous channels (e-mail and git). 

Anne proposed [FINISH] or [REPLACE] as the indicator.  

Caden has proposed [INCOMPLETE].

Let's vote by reply to this thread.  Vote closes 4/5 at noon AZ time.

**Comment by katecrombie** [comment]
[INCOMPLETE]

**Comment by cgobat** [comment]
cc @acraugh @benjhirsch

and anyone else whose GitHub handle I don't know

**Comment by acraugh** [comment]
[INCOMPLETE] for missing data and [CHECK] for questionable items works for me!

**Comment by acraugh** [comment]
I've drafted a document to cover what I guess we could call "best practices", although it would more accurately be called "Anne practices" at this point. I included the two flag value previously mentioned.

**Comment by cgobat** [comment]
Cool, sounds like a plan then. I'll close this as completed.
