### ISSUE TITLE
Retain nh:Engineering_Unit_Conversion

### ISSUE THREAD

**Issue by acraugh** [pds-data-dictionaries/ldd-nh#18]
This class has been added to schema and documentation as part of the 'fixup' work, but I think it's still an open question whether this will remain part of the primary data label, or if the engineering data will be presented as a separate data object. 

It's east enough to remove classes and documentation. Presumably, this will be decided well before version 1.1.0 is released.

**Comment by acraugh** [comment]
@cgobat, I'm assigning this to you for the decision-making part. If you want me to step in for documentation updates, let me know.

**Comment by cgobat** [comment]
Sounds good, thanks.

**Comment by cgobat** [comment]
@katecrombie and I have decided that we'd like to remove this from the dictionary and instead go down the path of including the conversion information as a secondary product.

**Comment by acraugh** [comment]
Okey-doke. Do you want to make those changes or do you want me to?

**Comment by acraugh** [comment]
Changes are made and merged.
