### ISSUE TITLE
Overall development tracking - who's doing what?

### ISSUE THREAD

**Issue by cgobat** [pds-data-dictionaries/ldd-nh#21]
Let's use this issue to track who is doing what so that we can stay on top of things and hopefully avoid conflicts. Here's what I know as far as instrument-specific class/attribute development is concerned:

- **Alice:** done by Adeline[^1] and merged in #25. Documentation and regression tests needed (ref: #27)
- **LEISA:** done by @katecrombie / @cgobat (merged in #12)
- **LORRI:** done(?) by @benjhirsch, merged in #25. Pending removal of binning attribute (ref: #16)? Documentation and regression tests needed (ref: #27).
- **MVIC:** done many moons ago by @acraugh &amp; co.
- **PEPSSI:** nothing PEPSSI-specific needed in mission LDD
- **REX:** done by @cgobat, awaiting PR review (branch: [feature/rex](https://github.com/pds-data-dictionaries/ldd-nh/tree/feature/rex), PR: #22)
- **SDC:** nothing SDC-specific needed in mission LDD
- **SWAP:** done by @katecrombie / @cgobat (merged in #11)&mdash;just one class containing a single attribute

This text will be updated as development progresses.

We also have generally-applicable classes like `nh:Observation_Parameters` (with subclasses such as `nh:Detector` and `nh:Spacecraft_State`) and `nh:Radiometric_Conversion_Constants`. Does anyone foresee a need for any more such things?

[^1]: Does Adeline have a GitHub account I can @mention?

**Comment by katecrombie** [comment]
**SDC:** I have completed my analysis of the SDC raw and calibrated products.  No additional attributes or classes are needed in the NH LDD.  These products are tabular, and specific descriptions will be included in the field descriptions.

**Comment by cgobat** [comment]
Great! I'll update the original post to reflect that.

**Comment by cgobat** [comment]
Given that I think this dictionary is now at least feature-complete,[^1] I am going to close this issue. If anyone objects or has further use for this ticket, feel free to reopen it.

[^1]: Except for REX, but that work is being tracked already/independently in #22
